# -*- coding: utf-8 -*-
"""regra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IxEiedE6VqG2ILvuPihq8dx1TaRcQiy3
"""

import yara
import os       #sys e os foram importados junto com a regra para ajudar o arquivo a rodar em qualquer pasta/local
import sys

regra_yara = """
rule VirusSimuladoBat
{
    meta:
        autor = "Grupo 1"
        descricao = "Detecta o script de lote de simulacao de virus"

    strings:
        // Identificador unico no script .bat
        $assinatura = "ASSINATURA_VIRUS_XYZ789"

        // Comandos comuns usados no script para efeitos visuais
        $cmd_color = "color"
        $cmd_title = "title"
        $cmd_start = "start"
        $cmd_echo = "echo Todos os seus arquivos pertencem a nos"

    condition:
        // O arquivo deve conter a assinatura unica e pelo menos 3 das outras strings
        $assinatura and 3 of ($cmd*)
}
"""

def escanear_arquivo(caminho_arquivo):
    """
    Escaneia um unico arquivo com base na regra Yara.
    """
    try:
        regras = yara.compile(source=regra_yara)
        matches = regras.match(filepath=caminho_arquivo)

        if matches:
            print(f"✔️  Possivel arquivo malicioso encontrado: {caminho_arquivo}")
            for match in matches:
                print(f"    Regra: {match.rule}")

                for s in match.strings:
                    for instance in s.instances:
                        print(f"        String {s.identifier} encontrada no offset {instance.offset}")
        else:
            print(f"❌  Nenhuma ameaca encontrada em: {caminho_arquivo}")

    except yara.Error as e:
        print(f"Erro ao compilar a regra Yara: {e}")
    except FileNotFoundError:
        print(f"Erro: Arquivo nao encontrado em {caminho_arquivo}")

if __name__ == "__main__":
    try:
        script_dir = os.path.dirname(sys.argv[0])
        arquivo_para_escanear = os.path.join(script_dir, "virus.bat")

        if os.path.exists(arquivo_para_escanear):
            escanear_arquivo(arquivo_para_escanear)
        else:
            print(f"❌ Erro: Arquivo 'virus.bat' nao encontrado.")
            print(f"   Certifique-se que 'virus.bat' esta na mesma pasta que este script.")
            print(f"   Pasta atual: {script_dir}")

    except Exception as e:
        print(f"Ocorreu um erro inesperado: {e}")